[google_service_account]
type = "service_account"
project_id = "ninth-potion-464513-a2"
private_key_id = "71ea45dcecf2ac0cb1eaad168d600e158e4a9fb7"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC0vFYuAJcuYHyz
1sJtUZwv1sh6Eti5LD3JyTJYUTea511xqnkyC61BVTmQBHBeohsb27YOqwu68gPA
ptXREA2Uvv6kJVQHi7xjNwXOIUi2Ewf1JEn99H2y7YRER+FvbJzgjVr1MQY97Oz7
yJM+OA7BjX2Es4L2CSzi+gXma0IA85eOLOck5jVilGhH6UH/VNarjqi+NctER92X
+qeOjr8P7jXP0+9iYRC0DbHo8l/c0t/YS2ksVl4P42FroLKCf0QioW1/MYwQGNwy
JxugO8U7as+3MCg+dnRdb1woH5gZ4Jyf2s6O9rXprafXVOAxBo4X5zmKlYRQFiKn
kpxZy2H7AgMBAAECggEAUGWrLGGE3tN7BYDWEk0IXlt76JmzoIOmpLmEVLckNhsP
fT2pFfMNyg9AQOlIl0AjMPxGezXpTOrVcoCEgrBSakWf/qLAQ28MiVHzmiNCNgQ3
OPxAkeCNfeecO8eB58/35QfcW0/IiAl5zfMGVNoY7k6jdEFqU0n3lqxDraEuxj7V
sEMEbKNBDbitovdexNMrsutaViOkxFOqoz9Itk6VXwan954fzu4AMWfGuullVn1w
RLWGfppGWcOfibKV25CJQ97j+D5tBuyrqP7oNZhgp/KSA1aOIcmmJ2FGB/Fbftg+
4B8sV9VUa1rjd8v7WAn3aJCT8CeZ95V9h8KhCOYIgQKBgQDqHzdjzHqeDfvvErkl
ikBa4xBp7SvOnPbzHDVTwo9mCfPxNsBscPaX2BtsoOFCENLuXnwSQlR+/MoSFrvE
fqzcbCUQhEC2f6tgfwNJ338ewMBC5874d6BW5eHFqDpQ3ifr4Ee25GfOdB2d4AKy
rpVL7jnd5OYOif7RvL0UswzAOwKBgQDFn/zE5oe6n17QBbvkv1E6SHHD1Kp02ghm
kDtZCLndTsGlfylzvgDZncQ882oYPUVsNc0HO1mhtflO7wNVmOpYJhydIErx824i
/FOj6Qmo5CLKyfui02MAipHMndhW8PFJv+8mrGD511bZIKRDg+N7KoLy6l4eQhZS
ouELPh2JQQKBgD9jVEvhARHqF1wTZa2UUPhKohcL7+Bw/yuzZ3zWIJ0v9KxKdq7l
pt5V1JcEt/h7NaD0VANdkiMPrmZXYV9CLOtBHIfsRtkil/P4b5uAt5pL9cInoRIE
0ZS1iPtLIP7kJ0rl3oTWMoTjS2GDVTerrSBxz5kUcHVfR27h+w+vqrQhAoGBAKtv
gkL9CLloD0O99aUWIkzBE4+iKMx9Z9QxQoqV+0Z0T6BVk4wIQ4yEQ/vr3Rlx7YtV
kKq5XaPezIsg5G+Y25HkXeYgYWNKnTxUT+pc+jg8z8HDPjudzMBndNtgApBJK8ei
bL/LwcR6faiVnGnFO81Yr4gyr7rn8Z12Fms+UzkBAoGAfktIV2WojmrYhh9NEPE2
T4EFAL+5VCQR+X2GAXh+VVp1SfdThcMxFTaDWLsScPnza1PN5PSw5jyM7k4cIyt+
g84XFbeJDi+RJKfq0Lsnu3zG1cFgiKvGU4LuVDKxkOSgugbMA8RtBE/urNHb69Wy
DEkAdFPMDvDqRGA7XDsKs9w=
-----END PRIVATE KEY-----"""
client_email = "financas-service-account@ninth-potion-464513-a2.iam.gserviceaccount.com"
client_id = "103994311445129482147"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/financas-service-account%40ninth-potion-464513-a2.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
